spring.application.name=nivel1-llm-directo
server.port=8080
llm.provider=gemini
gemini.api.key=${GEMINI_API_KEY:AIzaSyDefjkYwTZVdr9cvYeRvVtXWHxEMPxmMbQ}
gemini.base-url=https://generativelanguage.googleapis.com/v1beta/openai
gemini.model=gemini-2.5-flash